import { Helmet } from "react-helmet";
import { FileText } from "lucide-react";

export default function Terms() {
  return (
    <>
      <Helmet>
        <title>Terms of Service | CrePic</title>
        <meta 
          name="description" 
          content="CrePic Terms of Service. Read our terms and conditions for using our free online tools." 
        />
      </Helmet>

      <div className="container px-4 py-12 mx-auto max-w-4xl">
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-primary/10 mb-6">
            <FileText className="h-8 w-8 text-primary" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
          <p className="text-lg text-muted-foreground">
            Last updated: November 22, 2025
          </p>
        </div>

        <article className="prose prose-slate dark:prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-bold mb-4">Agreement to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing and using CrePic, you agree to be bound by these Terms of Service and all applicable laws and regulations. 
              If you do not agree with any of these terms, you are prohibited from using this website.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Use License</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Permission is granted to use CrePic's tools for personal and commercial purposes, subject to the following conditions:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>You may use the tools for any lawful purpose</li>
              <li>You may not attempt to reverse engineer or copy the source code</li>
              <li>You may not use the service to harm others or violate their rights</li>
              <li>You may not overload or attempt to disrupt the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Service Availability</h2>
            <p className="text-muted-foreground leading-relaxed">
              CrePic strives to provide continuous access to our tools, but we do not guarantee uninterrupted availability. 
              We reserve the right to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground mt-4">
              <li>Modify, suspend, or discontinue any tool at any time</li>
              <li>Perform maintenance that may temporarily affect availability</li>
              <li>Update features and functionality without prior notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Disclaimer of Warranties</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              CrePic is provided "as is" without any warranties, expressed or implied. We do not warrant that:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>The service will meet your specific requirements</li>
              <li>The service will be uninterrupted, timely, secure, or error-free</li>
              <li>The results obtained from using the service will be accurate or reliable</li>
              <li>Any errors in the software will be corrected</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              In no event shall CrePic or its creators be liable for any damages (including, without limitation, 
              damages for loss of data or profit, or due to business interruption) arising out of the use or inability 
              to use the tools on CrePic, even if CrePic has been notified orally or in writing of the possibility of such damage.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">User Content and Responsibility</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              You are solely responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Any content you process using our tools</li>
              <li>Ensuring you have the right to process such content</li>
              <li>Complying with all applicable laws regarding your content</li>
              <li>The accuracy and quality of output generated by our tools</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              Since all processing happens locally in your browser, CrePic never has access to your content. 
              However, you remain responsible for how you use the processed content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              The CrePic website, including its design, code, and functionality, is owned by CrePic and protected by 
              international copyright, trademark, and other intellectual property laws. You may not copy, modify, or 
              distribute any part of the website without express written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Third-Party Links</h2>
            <p className="text-muted-foreground leading-relaxed">
              CrePic may contain links to third-party websites or services. We are not responsible for the content, 
              privacy policies, or practices of any third-party sites. We encourage you to review the terms and policies 
              of any third-party sites you visit.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Advertising</h2>
            <p className="text-muted-foreground leading-relaxed">
              CrePic displays advertisements to support the free operation of the service. By using CrePic, you agree 
              to the display of these advertisements. We use Google AdSense, which may collect data as described in our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Prohibited Uses</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              You may not use CrePic:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>In any way that violates any applicable national or international law or regulation</li>
              <li>To transmit any harassing, libelous, abusive, threatening, or otherwise unlawful material</li>
              <li>To impersonate or attempt to impersonate CrePic or another user</li>
              <li>In any way that could damage, disable, or impair the service</li>
              <li>To engage in any automated use of the system</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Modifications to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to revise these Terms of Service at any time. By continuing to use CrePic after 
              changes are posted, you agree to be bound by the revised terms. Please check this page periodically for updates.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms of Service shall be governed by and construed in accordance with the laws of the jurisdiction 
              in which CrePic operates, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">Contact Information</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms of Service, please contact us through our Contact page.
            </p>
          </section>
        </article>
      </div>
    </>
  );
}
