#!/usr/bin/env node
/**
 * Generates src/data/blog-posts-meta.ts (slug/title/description/category/date/readTime/author/keywords only)
 * from src/data/blog-content.ts — run after every publish.
 * Result is ~10x smaller than blog-content.ts for faster BlogList / RecentBlogPosts loading.
 */
import { readFileSync, writeFileSync } from 'fs';

const BLOG_FILE = 'src/data/blog-content.ts';
const META_FILE = 'src/data/blog-posts-meta.ts';

const content = readFileSync(BLOG_FILE, 'utf-8');

// Collect all slug positions to segment the file
const slugPositions = [];
const slugRe = /slug:\s*[`'"]([^`'"]+)[`'"]/g;
let m;
while ((m = slugRe.exec(content)) !== null) {
  slugPositions.push({ slug: m[1], pos: m.index });
}

function extractStr(seg, field) {
  // backtick
  const btM = new RegExp(`${field}:\\s*\`([^\`]*)\``).exec(seg);
  if (btM) return btM[1];
  // single-quote
  const sqM = new RegExp(`${field}:\\s*'([^']*)'`).exec(seg);
  if (sqM) return sqM[1];
  // double-quote
  const dqM = new RegExp(`${field}:\\s*"([^"]*)"`).exec(seg);
  if (dqM) return dqM[1];
  return '';
}

function extractKeywords(seg) {
  const rm = /keywords:\s*\[([^\]]*)\]/s.exec(seg);
  if (!rm) return [];
  const items = [];
  const ir = /[`'"]([^`'"]*)[`'"]/g;
  let im;
  while ((im = ir.exec(rm[1])) !== null) {
    if (im[1].trim()) items.push(im[1]);
  }
  return items;
}

const metas = [];
for (let i = 0; i < slugPositions.length; i++) {
  const start = slugPositions[i].pos;
  const end = i + 1 < slugPositions.length ? slugPositions[i + 1].pos : content.length;
  const seg = content.slice(start, end);
  const slug = slugPositions[i].slug;
  const title = extractStr(seg, 'title');
  if (!title) continue;
  metas.push({
    slug,
    title,
    description: extractStr(seg, 'description'),
    category: extractStr(seg, 'category') || 'guide',
    publishDate: extractStr(seg, 'publishDate'),
    readTime: extractStr(seg, 'readTime'),
    author: extractStr(seg, 'author'),
    keywords: extractKeywords(seg),
  });
}

const lines = [
  '// AUTO-GENERATED by scripts/gen-meta.mjs — do not edit manually',
  '',
  'export interface BlogPostMeta {',
  '  slug: string;',
  '  title: string;',
  '  description: string;',
  '  category: string;',
  '  publishDate: string;',
  '  readTime: string;',
  '  author: string;',
  '  keywords: string[];',
  '}',
  '',
  `export const blogPostsMeta: BlogPostMeta[] = [`,
];

for (const m of metas) {
  const kws = '[' + m.keywords.map(k => JSON.stringify(k)).join(', ') + ']';
  lines.push('  {');
  lines.push(`    slug: ${JSON.stringify(m.slug)},`);
  lines.push(`    title: ${JSON.stringify(m.title)},`);
  lines.push(`    description: ${JSON.stringify(m.description)},`);
  lines.push(`    category: ${JSON.stringify(m.category)},`);
  lines.push(`    publishDate: ${JSON.stringify(m.publishDate)},`);
  lines.push(`    readTime: ${JSON.stringify(m.readTime)},`);
  lines.push(`    author: ${JSON.stringify(m.author)},`);
  lines.push(`    keywords: ${kws},`);
  lines.push('  },');
}

lines.push('];');
lines.push('');
lines.push('export function getAllBlogMeta(): BlogPostMeta[] {');
lines.push('  return [...blogPostsMeta].reverse();');
lines.push('}');
lines.push('');

writeFileSync(META_FILE, lines.join('\n'), 'utf-8');
console.log(`Generated ${metas.length} post metas → ${META_FILE}`);
