// AUTO-GENERATED by scripts/sync-indexable-content.mjs - do not edit manually
import type { BlogPostMeta } from "./blog-posts-meta";

export const recentBlogPostsMeta: BlogPostMeta[] = [
  {
    slug: "runway-vs-capcut-ai-editing-tools",
    title: "Runway vs CapCut: AI 영상 편집 도구 어느 것이 더 실용적인가",
    description: "AI 영상 편집 도구의 양대 산맥인 Runway와 CapCut을 기능·가격·학습 곡선·실제 활용도 측면에서 비교 분석합니다. 목적에 맞는 도구 선택 기준을 제시합니다.",
    category: "insights",
    publishDate: "2026-05-18",
    readTime: "9분",
    author: "이지수",
    keywords: ["Runway AI", "CapCut", "AI 영상 편집", "영상 편집 도구 비교", "AI 크리에이터 도구"],
  },
  {
    slug: "apple-podcast-keyword-optimization-tips",
    title: "Apple Podcast 키워드 최적화 팁: 팟캐스트 앱에서 발견되는 에피소드 만들기",
    description: "Apple Podcast 검색 알고리즘의 작동 방식을 이해하고 에피소드 제목·설명·태그를 최적화하는 실전 전략을 소개합니다. 팟캐스트 앱에서 새 청중을 자연 유입시키는 방법을 알아보세요.",
    category: "tips",
    publishDate: "2026-05-18",
    readTime: "10분",
    author: "이지수",
    keywords: ["Apple Podcast SEO", "팟캐스트 최적화", "팟캐스트 키워드", "팟캐스트 발견성", "팟캐스트 성장"],
  },
  {
    slug: "blogshortform-usage-tips",
    title: "웨비나 영상을 블로그·숏폼·뉴스레터로 재활용하는 팁",
    description: "한 번 제작한 웨비나 영상을 블로그 포스트, 숏폼 영상, 뉴스레터로 전환하는 실전 콘텐츠 재활용 전략을 단계별로 설명합니다. 제작 시간을 줄이고 채널별 성과를 동시에 높이세요.",
    category: "tips",
    publishDate: "2026-05-18",
    readTime: "9분",
    author: "김민혁",
    keywords: ["콘텐츠 재활용", "웨비나 활용", "숏폼 영상", "블로그 콘텐츠", "뉴스레터 전략"],
  },
];
